apiVersion: v1
kind: Service
metadata:
  name: threat-api-svc
  tier: backend
spec:
  type: NodePort
  selector:
    app: threat_api
    tier: backend
  ports:
      port: 8000
      targetPort: 8000
      NodePort: 30080